name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4

            - name: Install node modules
              run: npm ci

            - name: Run Tests
              run: npm run test

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build
